#!/bin/bash
set -e
finish() { if [ $? -gt 0 ]; then echo-red FAILED; exit 1; fi; }
trap finish EXIT

if [ -t 1 ]; then
    echo-green() { echo -ne "\e[32m"; echo -n "$@"; echo -e "\e[0m"; }
    echo-red() { echo -ne "\e[31m"; echo -n "$@"; echo -e "\e[0m"; }
else
    echo-green() { echo "$@"; }
    echo-red() { echo "$@"; }
fi

export NVMDIR="$PWD/.nvm"

function nvm-init () {
    [ -d "$NVMDIR" ] || git clone https://github.com/nvm-sh/nvm.git "$NVMDIR"
    ( cd "$NVMDIR"; git pull )
    set +e
    [ -s "$NVMDIR/nvm.sh" ] && \. "$NVMDIR/nvm.sh"
    set -e
    nvm install
    nvm use
}

function build () {
    rm -rf .nvm node_modules/ build/ server-build/ dist/
    nvm-init
    npm install
    npm run build-client
    npm run build-server
    mkdir dist/
    cp -pr .nvm .nvmrc node_modules service.sh dist/
    cp -pr build dist/frontend
    cp -pr server-build dist/backend
    echo-green Finished building project to dist/
}

if [ -z "$1" ]; then
    cat <<EOF

Usage:
  ./script build                        Do a project production build
EOF
else
    "$@"
fi
